language: objective-c
osx_image: xcode7
before_install: gem install cocoapods xcpretty obcd slather -N
xcode_sdk: iphonesimulator9.0
xcode_project: Neon.xcodeproj
xcode_scheme: NeonUnitTests
after_success: slather
